# Web scraping

Web scraping is a technique used to extract data from websites. It involves sending HTTP requests to websites, parsing the returned HTML code, and extracting the desired data. Web scraping is a powerful tool for data scientists as it allows them to collect large amounts of data from the web. This data can then be used to train machine learning models, analyse trends, and make informed business decisions.

---
## 1.&nbsp; Import libraries 💾

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

---
## 2.&nbsp; Beautiful Soup 🍲

[Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) is a Python library that simplifies the process of web scraping. It provides a user-friendly interface for parsing HTML documents, enabling users to extract specific information from websites. Through Beautiful Soup, you can navigate the HTML tree structure, locate elements based on their tags, attributes, and content, and extract the desired data into a structured format.

To illustrate how to use Beautiful Soup, we'll use the simplified mock website below. This stripped-down version serves as a practical learning tool, as real websites often possess much larger and more complex HTML structures. By starting with this simplified model, you can gradually build your skills and expertise, ensuring a solid understanding of the core concepts before tackling more intricate web scraping tasks.

In [2]:
html_doc = """
<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1" meta="Eldest sister">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2" meta="Middle sister">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3" meta="Youngest sister">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""


Beautiful Soup's HTML parser takes the raw, unruly HTML code and transforms it into a neatly organised tree structure, making the information easily accessible and manageable.

In [3]:
soup = BeautifulSoup(html_doc, 'html.parser')

We can see the tree structure using Beautiful Soup's `.prettify()` method.

In [4]:
print(soup.prettify())

<html>
 <head>
  <title>
   The Dormouse's story
  </title>
 </head>
 <body>
  <p class="title">
   <b>
    The Dormouse's story
   </b>
  </p>
  <p class="story">
   Once upon a time there were three little sisters; and their names were
   <a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">
    Elsie
   </a>
   ,
   <a class="sister" href="http://example.com/lacie" id="link2" meta="Middle sister">
    Lacie
   </a>
   and
   <a class="sister" href="http://example.com/tillie" id="link3" meta="Youngest sister">
    Tillie
   </a>
   ;
and they lived at the bottom of a well.
  </p>
  <p class="story">
   ...
  </p>
 </body>
</html>

---
## 3.&nbsp; Navigating html for beginners 🧭
There are many methods in Beautiful Soup to explore the html data. By far the most popular and useful of these is `.find_all().` So, naturally, this is where we'll start our journey.

### 3.1.&nbsp; `.find_all()`
The `.find_all()` method in Beautiful Soup returns a list of all the elements that match the specified criteria, such as tag name, class name, or attribute values.

#### 3.1.1.&nbsp; Searching by tag

The tags are the letter/word at the beginning of the angle brackets. For example, below, these brackets have an `a` tag.

`<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>`

The `.find_all()` method takes a string argument and returns a list of all matching HTML tags within the current document. If no matching tags exist, an empty list is returned.

In [5]:
soup

<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>
<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2" meta="Middle sister">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3" meta="Youngest sister">Tillie</a>;
and they lived at the bottom of a well.</p>
<p class="story">...</p>
</body></html>

In [6]:
soup.find_all("title")

In [7]:
soup.find_all("p")[1]

<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2" meta="Middle sister">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3" meta="Youngest sister">Tillie</a>;
and they lived at the bottom of a well.</p>

#### 3.1.2.&nbsp; Searching by attribute

Attributes are the other information in the angle brackets. For example, below, these brackets have a `class`, `href`, `id`, and `meta` attribute.

`<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>`

Attributes provide additional context and functionality to the elements. They can serve various purposes, including CSS selectors for styling, URLs for linking to external resources, metadata for storing relevant data, and a multitude of other information-bearing components. By leveraging these attributes, we can effectively target specific sections of the website.

##### 3.1.2.1.&nbsp; CSS selectors
CSS selectors are used to to style certain sections of websites. This makes them very helpful for webscraping as we can then target certain regions of the website.

###### 3.1.2.1.1.&nbsp; Class
Class selectors are used to style **multiple** HTML elements that share a common characteristic or function.
> **Note:** here class has an underscore at the end of the word, this is because class is a reserved keyword in python.

In [8]:
soup.find_all(class_="sister")

[<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2" meta="Middle sister">Lacie</a>,
 <a class="sister" href="http://example.com/tillie" id="link3" meta="Youngest sister">Tillie</a>]

###### 3.1.2.1.2.&nbsp; ID
ID selectors are used to style **single** HTML elements.

In [9]:
soup.find_all(id="link1")

In [10]:
soup.find_all(id="link2")

##### 3.1.2.2.&nbsp; Other attributes
HTML elements can also include other attributes, which can be equally useful for identifying and targeting specific data points. To locate these attributes, search for them using the same method as you do for CSS selectors.

In [11]:
soup.find_all(meta="Youngest sister")

#### 3.1.3.&nbsp; Searching by string
The text (string) is the part between the opening and closing angle brackets, this is what's displayed on the webpage. For example, below, these brackets have `Elsie` as the text.

`<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>`

Instead of searching for specific tags or attributes, you can also search for this text. To do this, you can use a string or a regular expression to specify the text you're looking for.

In [12]:
soup.find_all(string="Dormouse")

[]

The string "Dormouse" didn't return any results because BeautifulSoup searches for entire strings that exactly match the string you entered. In other words, the string must be the exact same as what you're searching for for it to be considered a match.

In [13]:
soup.find_all(string="The Dormouse's story")

["The Dormouse's story", "The Dormouse's story"]

To search for a substring, the easiest way is to use the regular expressions method `.compile()`.

In [14]:
import re
soup.find_all(string=re.compile("sister", re.IGNORECASE))

['Once upon a time there were three little sisters; and their names were\n']

> **Note:** by default, the .compile() method is case-sensitive, meaning it will only match strings that are exactly equal to the pattern you specify, including case. To perform case-insensitive matching, you must explicitly pass the re.IGNORECASE flag to the .compile() method.

### 3.2.&nbsp; Extracting text
There are a few ways to extract text in Beautiful Soup, here we'll focus on 2 of them.

#### 3.2.1.&nbsp; `.get_text()`
The `.get_text()` method extracts all the human-readable text from a Beautiful Soup object, returning it as a string.

In [15]:
soup.find_all("title")

In [16]:
soup.find_all("title").get_text()

AttributeError: ResultSet object has no attribute "get_text". You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

> Read the error message and look at the output from the cell above. Can you work out why we got an error?

In [17]:
# @title Click `show code` to see the solution to the error

# It was a list, read the error messages and notice the square brackets in the original output
# Therefore, we need to select the first and only element of this list
soup.find_all("title")[0].get_text()

"The Dormouse's story"

We can also print out multiple items using our looping skills.

In [18]:
story = soup.find_all("p")
story

[<p class="title"><b>The Dormouse's story</b></p>,
 <p class="story">Once upon a time there were three little sisters; and their names were
 <a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2" meta="Middle sister">Lacie</a> and
 <a class="sister" href="http://example.com/tillie" id="link3" meta="Youngest sister">Tillie</a>;
 and they lived at the bottom of a well.</p>,
 <p class="story">...</p>]

In [19]:
for p in story:
  print(p.get_text())

The Dormouse's story
Once upon a time there were three little sisters; and their names were
Elsie,
Lacie and
Tillie;
and they lived at the bottom of a well.
...

#### 3.2.2.&nbsp; Extracting attributes:
HTML elements often store additional information within their attributes. To extract this data using Beautiful Soup, you can append square brackets after the element selector and specify the attribute name within them.

In [20]:
soup.find_all(id="link1")

In [21]:
soup.find_all(id="link1")[0]['href']

'http://example.com/elsie'

In [22]:
soup.find_all(id="link1")[0]['meta']

'Eldest sister'

## Challenge 1 😀
Below is new HTML code. Use your scrapping skills to answer the questions.

In [23]:
geography = """
<!DOCTYPE html>
<html>
<head> Geography</head>
<body>

<div class="city">
  <h2>London</h2>
  <p>London is the most popular tourist destination in the world.</p>
</div>

<div class="city">
  <h2>Paris</h2>
  <p>Paris was originally a Roman City called Lutetia.</p>
</div>

<div class="country">
  <h2>Spain</h2>
  <p>Spain produces 43,8% of all the world's Olive Oil.</p>
</div>

</body>
</html>
"""

In [24]:
# Create the "soup"
soup2 = BeautifulSoup(geography, 'html.parser')

In [25]:
# 1. All the "fun facts"
for p in soup2.find_all("p"):
    print(p.get_text())

London is the most popular tourist destination in the world.
Paris was originally a Roman City called Lutetia.
Spain produces 43,8% of all the world's Olive Oil.

In [26]:
# 2. The names of all the places.
for h2 in soup2.find_all("h2"):
    print(h2.get_text())

London
Paris
Spain

In [27]:
# 3. All the content (name and fact) of all the cities (only cities, not countries!)
for div in soup2.find_all(class_ = "city"):
    print(div.get_text())

London
London is the most popular tourist destination in the world.


Paris
Paris was originally a Roman City called Lutetia.

In [28]:
# 4. The names (not facts!) of all the cities (not countries!)
for div in soup2.find_all(class_ = "city"):
    print(div.find("h2").get_text())

London
Paris

---
## 4.&nbsp; Navigating html with a few more advanced techniques 🗺️

### 4.1.&nbsp; `.find()`
`.find()` is similar to `.find_all()`, but it returns only the first element that matches the specified criteria. This makes it useful when you know exactly where the element you're looking for is located and you only need to retrieve one instance of it.

In [29]:
soup.find('p')

### 4.2.&nbsp; `.select()`
`.select()` is similar to `.find_all()`, but there are 2 main differences:
- the way we write our query in the brackets is slightly different
- `.select()` allows you to chain CSS selectors together to navigate through the HTML structure, enabling you to select elements based on their positions within nested elements or patterns. This makes it particularly useful for extracting data from complex HTML structures.

In contrast, `.find_all()` uses a simpler syntax based on tag names and attributes, making it more straightforward for basic element selection.

Here's how we query with `.find_all()`

In [30]:
soup.find_all('a', class_='sister')

[<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2" meta="Middle sister">Lacie</a>,
 <a class="sister" href="http://example.com/tillie" id="link3" meta="Youngest sister">Tillie</a>]

Here's the same query with `.select()`

In [31]:
soup.select('a.sister')

[<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2" meta="Middle sister">Lacie</a>,
 <a class="sister" href="http://example.com/tillie" id="link3" meta="Youngest sister">Tillie</a>]

To demonstrate the power of `.select()` in navigating through nested elements, let's extract all the `<a>` tags with the id `'link2'` that are within `<p>` tags with the class `'story'`.

In [32]:
soup.select('p.story a#link2')

### 4.3.&nbsp; Navigating to the Next or Previous Element
In some cases, you may need to access specific elements that are closely related to others, but their HTML structure doesn't provide unique identifiers. To overcome this challenge, you can utilise the `.find_next()` and `.find_previous()` methods to navigate through the HTML structure and reach the desired element.

In [33]:
soup

<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>
<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2" meta="Middle sister">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3" meta="Youngest sister">Tillie</a>;
and they lived at the bottom of a well.</p>
<p class="story">...</p>
</body></html>

In [34]:
last_link = soup.find(id='link3')
last_link

#### 4.1.1.&nbsp; `.find_next()`
`.find_next()` moves forward one element

In [35]:
last_link.find_next()

#### 4.2.&nbsp; `.find_previous()`
`.find_previous()` moves back one element

In [36]:
second_to_last = last_link.find_previous()

In [37]:
second_to_last.find_previous()

---
## 5.&nbsp; Showcasing these skills on a real website 💻
Let's see what information we can get from the wikipedia site for web scraping

### Loading the html

In [38]:
url = "https://en.wikipedia.org/wiki/Web_scraping"
headers = {'User-Agent': 'Chrome/134.0.0.0'}

response = requests.get(url, headers=headers)

In [39]:
response.content

b'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>Web scraping - Wikipedia</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split(\'%2C\').forEach(function(pref){className=className.replace(new RegExp(\'(^| )\'+pref.replace(/-clientpref-\\w+$|[^\\w-]+/g,\'\')+\'-clientpref-\\\\w+( |$)\'),\'$1\'+pref+\'$2\');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"d2865702-b4a8-46a0-a7ef-fd8a19fbfbe2","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Web_scraping","wgTitle":"Web scraping","wgCurRevisionId":1368486598,"wgRevisionId":1368486598,"wgArticleId":2696619,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Articles needing additional references from April 2023","All articles needing additional references","All articles with unsourced statements","Articles with unsourced statements from January 2026","Articles needing cleanup from October 2025","All pages needing cleanup","Articles containing how-to sections","Articles with limited geographic scope from October 2015","United States-centric","CS1 maint: multiple names: authors list","Articles with unsourced statements from April 2023","CS1 Danish-language sources (da)","CS1 French-language sources (fr)","Web scraping"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Web_scraping","wgRelevantArticleId":2696619,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":40000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Computing":{"class":"C","importance":"Mid"},"Internet":{"class":"C","importance":"High"},"Project-independent assessment":{"class":"C","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q665452","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};\nRLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];</script>\n<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});\n}];});});</script>\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cmediawiki.skinning.content.parsoid%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022">\n<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>\n<meta name="ResourceLoaderDynamicStyles" content="">\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">\n<meta name="generator" content="MediaWiki 1.47.0-wmf.15">\n<meta name="referrer" content="origin">\n<meta name="referrer" content="origin-when-cross-origin">\n<meta name="robots" content="max-image-preview:standard">\n<meta name="format-detection" content="telephone=no">\n<meta name="viewport" content="width=1120">\n<meta property="og:title" content="Web scraping - Wikipedia">\n<meta property="og:type" content="website">\n<link rel="preconnect" href="//upload.wikimedia.org">\n<link rel="alternate" type="application/x-wiki" title="Edit this page" href="/w/index.php?title=Web_scraping&amp;action=edit">\n<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">\n<link rel="icon" href="/static/favicon/wikipedia.ico">\n<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="Wikipedia (en)">\n<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd">\n<link rel="canonical" href="https://en.wikipedia.org/wiki/Web_scraping">\n<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">\n<link rel="alternate" type="application/atom+xml" title="Wikipedia Atom feed" href="/w/index.php?title=Special:RecentChanges&amp;feed=atom">\n<link rel="dns-prefetch" href="//meta.wikimedia.org" />\n<link rel="dns-prefetch" href="auth.wikimedia.org">\n</head>\n<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Web_scraping rootpage-Web_scraping skin-vector-2022 action-view">\n<div id="mw-aria-live-region" class="mw-aria-live-region" aria-live="polite"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>\n<div class="vector-header-container">\n\t<header class="vector-header mw-header no-font-mode-scale">\n\t\t<div class="vector-header-start">\n\t\t\t<nav class="vector-main-menu-landmark" aria-label="Site">\n\t\t\t\t\n<div id="vector-main-menu-dropdown" class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right"  title="Main menu" >\n\t<input type="checkbox" id="vector-main-menu-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-main-menu-dropdown" class="vector-dropdown-checkbox "  aria-label="Main menu"   >\n\t<label id="vector-main-menu-dropdown-label" for="vector-main-menu-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>\n\n<span class="vector-dropdown-label-text">Main menu</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t\t<div id="vector-main-menu-unpinned-container" class="vector-unpinned-container">\n\t\t\n<div id="vector-main-menu" class="vector-main-menu vector-pinnable-element">\n\t<div\n\tclass="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned"\n\tdata-feature-name="main-menu-pinned"\n\tdata-pinnable-element-id="vector-main-menu"\n\tdata-pinned-container-id="vector-main-menu-pinned-container"\n\tdata-unpinned-container-id="vector-main-menu-unpinned-container"\n>\n\t<div class="vector-pinnable-header-label">Main menu</div>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin" aria-label="Move Main menu to sidebar">move to sidebar</button>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin" aria-label="Hide Main menu">hide</button>\n</div>\n\n\t\n<div id="p-navigation" class="vector-menu mw-portlet mw-portlet-navigation"  >\n\t<div class="vector-menu-heading">\n\t\tNavigation\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-mainpage-description" class="mw-list-item"><a href="/wiki/Main_Page" title="Visit the main page [z]" accesskey="z"><span>Main page</span></a></li><li id="n-contents" class="mw-list-item"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li id="n-currentevents" class="mw-list-item"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li id="n-randompage" class="mw-list-item"><a href="/wiki/Special:Random" title="Visit a randomly selected article [x]" accesskey="x"><span>Random article</span></a></li><li id="n-aboutsite" class="mw-list-item"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li id="n-contactpage" class="mw-list-item"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-interaction" class="vector-menu mw-portlet mw-portlet-interaction"  >\n\t<div class="vector-menu-heading">\n\t\tContribute\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-help" class="mw-list-item"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li id="n-introduction" class="mw-list-item"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li id="n-portal" class="mw-list-item"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li id="n-recentchanges" class="mw-list-item"><a href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]" accesskey="r"><span>Recent changes</span></a></li><li id="n-upload" class="mw-list-item"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li id="n-specialpages" class="mw-list-item"><a href="/wiki/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q"><span>Special pages</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n</div>\n\n\t\t\t\t</div>\n\n\t</div>\n</div>\n\n\t\t</nav>\n\t\t\t\n<a href="/wiki/Main_Page" class="mw-logo">\n\t<img class="mw-logo-icon" src="/static/images/icons/enwiki-25.svg" alt="" aria-hidden="true" height="50" width="50">\n\t<span class="mw-logo-container skin-invert">\n\t\t<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;">\n\t\t<img class="mw-logo-tagline" alt="The Free Encyclopedia" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" width="140" height="11" style="width: 8.75em; height: 0.6875em;">\n\t</span>\n</a>\n\n\t\t</div>\n\t\t<div class="vector-header-end">\n\t\t\t\n<div id="p-search" role="search" class="vector-search-box-vue  vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box">\n\t<a href="/wiki/Special:Search" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" title="Search Wikipedia [f]" accesskey="f"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>\n\n<span>Search</span>\n\t</a>\n\t<div class="vector-typeahead-search-container">\n\t\t<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">\n\t\t\t<form action="/w/index.php" id="searchform" class="cdx-search-input cdx-search-input--has-end-button">\n\t\t\t\t<div id="simpleSearch" class="cdx-search-input__input-wrapper"  data-search-loc="header-moved">\n\t\t\t\t\t<div class="cdx-text-input cdx-text-input--has-start-icon">\n\t\t\t\t\t\t<input\n\t\t\t\t\t\t\tclass="cdx-text-input__input mw-searchInput" autocomplete="off"\n\t\t\t\t\t\t\t type="search" name="search" placeholder="Search Wikipedia" aria-label="Search Wikipedia" autocapitalize="none" spellcheck="false" title="Search Wikipedia [f]" accesskey="f" id="searchInput"\n\t\t\t\t\t\t\t>\n\t\t\t\t\t\t<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>\n\t\t\t\t\t</div>\n\t\t\t\t\t<input type="hidden" name="title" value="Special:Search">\n\t\t\t\t</div>\n\t\t\t\t<button class="cdx-button cdx-search-input__end-button">Search</button>\n\t\t\t</form>\n\t\t</div>\n\t</div>\n</div>\n\n\t\t\t<nav class="vector-user-links vector-user-links-wide" aria-label="Personal tools">\n\t<div class="vector-user-links-main">\n\t\n<div id="p-vector-user-menu-preferences" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-userpage" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t<nav class="vector-appearance-landmark" aria-label="Appearance">\n\t\t\n<div id="vector-appearance-dropdown" class="vector-dropdown "  title="Change the appearance of the page&#039;s font size, width, and color" >\n\t<input type="checkbox" id="vector-appearance-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-appearance-dropdown" class="vector-dropdown-checkbox "  aria-label="Appearance"   >\n\t<label id="vector-appearance-dropdown-label" for="vector-appearance-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon"></span>\n\n<span class="vector-dropdown-label-text">Appearance</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t<div id="vector-appearance-unpinned-container" class="vector-unpinned-container">\n\t\t\t\t\n\t\t\t</div>\n\t\t\n\t</div>\n</div>\n\n\t</nav>\n\t\n<div id="p-vector-user-menu-notifications" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-overflow" class="vector-menu mw-portlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t<li id="pt-sitesupport-2" class="mw-list-item vector-menu-item--collapsible"><a data-mw-interface  href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en" data-mw-donate-attempt="top_link" class=""><span>Donate</span></a>\n</li>\n<li id="pt-createaccount-2" class="mw-list-item vector-menu-item--collapsible"><a data-mw-interface  href="/w/index.php?title=Special:CreateAccount&amp;returnto=Web+scraping" title="You are encouraged to create an account and log in; however, it is not mandatory" class=""><span>Create account</span></a>\n</li>\n<li id="pt-login-2" class="mw-list-item vector-menu-item--collapsible"><a data-mw-interface  href="/w/index.php?title=Special:UserLogin&amp;returnto=Web+scraping" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o" class=""><span>Log in</span></a>\n</li>\n\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t</div>\n\t\n<div id="vector-user-links-dropdown" class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out vector-user-links-dropdown--collapsible"  title="Log in and more options" >\n\t<input type="checkbox" id="vector-user-links-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-user-links-dropdown" class="vector-dropdown-checkbox "  aria-label="Personal tools"   >\n\t<label id="vector-user-links-dropdown-label" for="vector-user-links-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>\n\n<span class="vector-dropdown-label-text">Personal tools</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\n<div id="p-personal" class="vector-menu mw-portlet mw-portlet-personal"  title="User menu" >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t<li id="pt-sitesupport" class="mw-list-item vector-menu-item--collapsible"><a data-mw-interface  href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en" data-mw-donate-attempt="top_link" class=""><span class="vector-icon mw-ui-icon-heart mw-ui-icon-wikimedia-heart cdx-button__icon"></span>\n\n<span>Donate</span></a>\n</li>\n<li id="pt-createaccount" class="mw-list-item vector-menu-i

In [40]:
soup_3 = BeautifulSoup(response.content, 'html.parser')

> While we haven't yet looked into the requests library, we'll postpone delving into it today to avoid overwhelming you with too much new information. Instead, we'll explore the requests library when we start gathering weather data later in the project.

In [41]:
print(soup_3.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Web scraping - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"d2865702-b4a8-46a0-a7ef-fd8a19fbfbe2","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Web_scraping","wgTitle":"Web scraping","wgCurRevisionId":1368486598,"wgRevisionId":1368486598,"wgArticleId":2696619,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Articles needing additional references from April 2023","All articles needing additional references","All articles with unsourced statements","Articles with unsourced statements from January 2026","Articles needing cleanup from October 2025","All pages needing cleanup","Articles containing how-to sections","Articles with limited geographic scope from October 2015","United States-centric","CS1 maint: multiple names: authors list","Articles with unsourced statements from April 2023","CS1 Danish-language sources (da)","CS1 French-language sources (fr)","Web scraping"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Web_scraping","wgRelevantArticleId":2696619,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":40000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Computing":{"class":"C","importance":"Mid"},"Internet":{"class":"C","importance":"High"},"Project-independent assessment":{"class":"C","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q665452","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cmediawiki.skinning.content.parsoid%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.47.0-wmf.15" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="Web scraping - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//upload.wikimedia.org" rel="preconnect"/>
  <link href="/w/index.php?title=Web_scraping&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/Web_scraping" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch">
   <link href="auth.wikimedia.org" rel="dns-prefetch"/>
  </link>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Web_scraping rootpage-Web_scraping skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2">
           <a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2">
           <a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=Web+scraping" title="You are encouraged to create an account and log in; however, it is not mandatory">
            <span>
             Create account
            </span>
           </a>
          </li>
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-login-2">

### Getting the title

In [42]:
soup_3.find("title").get_text()

'Web scraping - Wikipedia'

### Getting the first h1 tag

In [43]:
soup_3.find("h1").get_text()

'Web scraping'

### Getting all the h2 tags

In [44]:
h2_tags = soup_3.find_all("h2")
h2_tags

[<h2 class="vector-pinnable-header-label">Contents</h2>,
 <h2 id="History">History</h2>,
 <h2 id="Techniques">Techniques</h2>,
 <h2 id="Legal_issues">Legal issues</h2>,
 <h2 id="Methods_to_prevent_web_scraping">Methods to prevent web scraping</h2>,
 <h2 id="See_also">See also</h2>,
 <h2 id="References">References</h2>]

As we have multiple tags in the list here, we need to use a loop to print them out.

In [45]:
for h2 in h2_tags:
  print(h2.get_text())

Contents
History
Techniques
Legal issues
Methods to prevent web scraping
See also
References

### Selecting the `Legal Issues` text for only `India`
> **Pro tip:** If you're using Google Chrome, you can navigate to `View > Developer > Inspect elements` to access the built-in web development tools. Here, you can explore the HTML structure of the webpage directly within the browser using your mouse. This interactive approach is often more intuitive than examining the raw HTML code.

By investigating the html we can see that the closest, easy to access, tag is the heading with the CSS `id` of `"India"`.

In [46]:
soup_3.find("h3", id="India")

We can then use `.find_next()` to select the text.

In [47]:
soup_3.find("h3", id="India").find_next()

<span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Web_scraping&amp;action=edit&amp;section=15" title="Edit section: India"><span>edit</span></a><span class="mw-editsection-bracket">]</span></span>

Looks like the next tag was a `span` tag, so let's specify that we want the next `p` tag.

In [48]:
soup_3.find("h3", id="India").find_next("p")

<p id="mwAUM">Besides a few cases dealing with IPR infringement, Indian courts have not expressly ruled on the legality of web scraping. However, since all common forms of electronic contracts are enforceable in India, violating the terms of use prohibiting data scraping will be a violation of the contract law. It will also violate the <a href="https://en.wikipedia.org/wiki/Information_Technology_Act,_2000#:~:text=From_Wikipedia,_the_free_encyclopedia_The_Information_Technology,in_India_dealing_with_cybercrime_and_electronic_commerce." id="mwAUQ" rel="mw:WikiLink" title="Information Technology Act, 2000">Information Technology Act, 2000</a>, which penalizes unauthorized access to a computer resource or extracting data from a computer resource.</p>

Now we can simply extract the text, and we have what we need

In [49]:
soup_3.find("h3", id="India").find_next("p").get_text()

'Besides a few cases dealing with IPR infringement, Indian courts have not expressly ruled on the legality of web scraping. However, since all common forms of electronic contracts are enforceable in India, violating the terms of use prohibiting data scraping will be a violation of the contract law. It will also violate the Information Technology Act, 2000, which penalizes unauthorized access to a computer resource or extracting data from a computer resource.'

### Selecting the `Legal Issues` text for all places

In [50]:
legal_text = {}

for section in soup_3.find("section", id="mwlA").find_all("section"):
    # print(section.find("h3").get_text())
    legal_text[section.find("h3").get_text()] = ""
    for p in section.find_all("p"):
        # print(p.get_text())
        legal_text[section.find("h3").get_text()] += p.get_text() + "\n"

In [51]:
print(legal_text["European Union"])

In February 2006, the Danish Maritime and Commercial Court (Copenhagen) ruled that systematic crawling, indexing, and deep linking by portal site ofir.dk of real estate site Home.dk does not conflict with Danish law or the database directive of the European Union.[28]
Ethical data scraping supports offmarket sourcing in business but must comply with GDPR to avoid privacy violations in automated data collection.[29]
In a February 2010 case complicated by matters of jurisdiction, Ireland's High Court delivered a verdict that illustrates the inchoate state of developing case law. In the case of Ryanair Ltd v Billigfluege.de GmbH, Ireland's High Court ruled Ryanair's "click-wrap" agreement to be legally binding. In contrast to the findings of the United States District Court Eastern District of Virginia and those of the Danish Maritime and Commercial Court, Justice Michael Hanna ruled that the hyperlink to Ryanair's terms and conditions was plainly visible, and that placing the onus on the user to agree to terms and conditions in order to gain access to online services is sufficient to comprise a contractual relationship.[30] The decision is under appeal in Ireland's Supreme Court.[31]
On April 30, 2020, the French Data Protection Authority (CNIL) released new guidelines on web scraping.[32] The CNIL guidelines made it clear that publicly available data is still personal data and cannot be repurposed without the knowledge of the person to whom that data belongs.[33]

## Challenge 2 😀

Utilise your web scraping skills to gather information about three German cities – Berlin, Hamburg, and Munich – from Wikipedia. You will start by extracting basic information: the country, the latitude and the longitude of each city and then expand to more dynamic data such as the population.

1. Scraping Basic Information

  1.1. Begin by scraping the country, the latitude and the longitude of each city from their respective Wikipedia pages:

 - Berlin: https://en.wikipedia.org/wiki/Berlin
 - Hamburg: https://en.wikipedia.org/wiki/Hamburg
 - Munich: https://en.wikipedia.org/wiki/Munich

  1.2. Once you have scraped the basic information of each city, reflect on the similarities and patterns in accessing them across the three pages. Also, analyse the URLs to identify any commonalities. Make a loop that executes once and retrieves the country, latitude, and longitude for all three cities.

In [52]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [53]:
url = "https://en.wikipedia.org/wiki/Berlin"
headers = {'User-Agent': 'Chrome/134.0.0.0'}

response = requests.get(url, headers=headers)
response.status_code

200

In [54]:
if response.status_code == 200:
    city_soup = BeautifulSoup(response.content, 'html.parser')

In [55]:
for row in city_soup.find("table").find_all("tr"):
    if row.find(string="Country"): 
        country = row.find("a").get_text()

In [56]:
lat, lon = city_soup.find("table").find(class_="geo").get_text().split("; ")

In [57]:
lon

'13.40500'

Test for other cities

In [58]:
url = "https://en.wikipedia.org/wiki/Hamburg"
response = requests.get(url, headers=headers)
if response.status_code == 200:
    city_soup = BeautifulSoup(response.content, 'html.parser')

In [59]:
for row in city_soup.find("table").find_all("tr"):
    if row.find(string="Country"): 
        country = row.find("a").get_text()
country

'Germany'

In [60]:
lat, lon = city_soup.find("table").find(class_="geo").get_text().split("; ")
lat, lon

('53.550', '10.000')

In [67]:
countries = []
latitudes = []
longitudes = []

cities = ["Berlin", "Hamburg", "Munich"]

for city in cities:
    url = f"https://en.wikipedia.org/wiki/{city}"
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        city_soup = BeautifulSoup(response.content, 'html.parser')
        for row in city_soup.find("table").find_all("tr"):
            if row.find(string="Country"): 
                countries.append(row.find("a").get_text())
        lat, lon = city_soup.find("table").find(class_="geo").get_text().split("; ")
        try:
            latitudes.append(float(lat))
            longitudes.append(float(lon))
        except ValueError:
            latitudes.append(None)
            longitudes.append(None)
            
    else:
        print(f"WARNING: Could not retrieve HTML for {city}")

2. Data Organisation

  2.1 Utilise pandas DataFrame to effectively store the extracted information. This DataFrame should have a row for each city, and columns for each type of information (cityname, country, latitude, longitude). If you feel brave, change latitude and longitude into decimal format.

  2.2 Looking ahead (optional): Create a function from the loop and DataFrame to encapsulate the scraping process. This function can be used repeatedly to fetch updated data whenever necessary. It should return a clean, properly formatted DataFrame.

In [68]:
cities_df = pd.DataFrame({"name": cities, "country": countries, "latitude": latitudes, "longitude": longitudes})
cities_df

      name  country  latitude  longitude
0   Berlin  Germany   52.5200     13.405
1  Hamburg  Germany   53.5500     10.000
2   Munich  Germany   48.1375     11.575

## BONUS Challenge 3: Population

  3.1. Expand the scope of your data gathering by extracting the population of a city. This information changes over time, so we might need to add a timestamp.

  3.2. Organise your information in a DataFrame and wrap it in a separate function.

In [69]:
city = cities_df["name"].iloc[0]
url = f"https://en.wikipedia.org/wiki/{city}"
response = requests.get(url, headers=headers)
if response.status_code == 200:
    city_soup = BeautifulSoup(response.content, 'html.parser')

In [70]:
for row in city_soup.find("table").find_all("tr"):
    if row.find(string="Population"): 
        population = int(row.find_next("td").get_text().replace(",", ""))

In [71]:
populations = []
for city in cities_df["name"]:
    url = f"https://en.wikipedia.org/wiki/{city}"
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        city_soup = BeautifulSoup(response.content, 'html.parser')
        for row in city_soup.find("table").find_all("tr"):
            if row.find(string="Population"): 
                population = int(row.find_next("td").get_text().replace(",", ""))
    populations.append(population)

In [72]:
pop_df = pd.DataFrame({"population": populations, "data_gathered": pd.Timestamp.now().date()})
pop_df

   population data_gathered
0     3596999    2026-08-24
1     1973896    2026-08-24
2     1505005    2026-08-24

## BONUS Challenge 4: Global Data Scraping

  With your robust scraping skills now honed, venture beyond the confines of Germany and explore other cities around the world. While the extraction methodology for German cities may follow a consistent pattern, this may not be the case for cities from different countries. Can you make a function that returns a clean DataFrame of information for cities worldwide?