# Weather forecasts from OpenWeatherMap API

API documentation: https://openweathermap.org/api/forecast5?collection=current_forecast

## Libraries and Constants

In [9]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

In [10]:
load_dotenv(override=True)
connection_string = os.getenv("CON_STRING")
openweather_key = os.getenv("OPENWEATHER_KEY")
print("Connection:", connection_string)
print("API Key:", openweather_key)

Connection: mysql+pymysql://root:Epityxia2026@127.0.0.1:3306/gans
API Key: aba351679836169313916c712cffdd1c

In [11]:
with open(".env", "w") as f:
    f.write("CON_STRING=mysql+pymysql://root:YOUR_PASSWORD@127.0.0.1:3306/gans\n")
    f.write("OPENWEATHER_KEY=your_api_key_here\n")

In [1]:
print(connection_string)

NameError: name 'connection_string' is not defined

In [13]:
load_dotenv()
connection_string = os.getenv("CON_STRING")
openweather_key = os.getenv("OPENWEATHER_KEY")

In [14]:
cities_df = pd.read_sql("cities", con=connection_string)
cities_df

   city_id     name  country  latitude  longitude
0        1   Berlin  Germany   52.5200     13.405
1        2  Hamburg  Germany   53.5500     10.000
2        3   Munich  Germany   48.1375     11.575

In [17]:
berlin = cities_df.loc[0]

url = "https://api.openweathermap.org/data/2.5/forecast"
params = {"lat": berlin["latitude"], "lon": berlin["longitude"], "appid": openweather_key, "units": "metric"}

response = requests.get(url, params=params)
response_json = response.json()
print(response_json.keys())

dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

In [18]:
print(response_json)

{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1787583600, 'main': {'temp': 20.69, 'feels_like': 20.46, 'temp_min': 20.69, 'temp_max': 22.25, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1016, 'humidity': 63, 'temp_kf': -1.56, 'dew_point': 13.4}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 95}, 'wind': {'speed': 1.43, 'deg': 307, 'gust': 1.68}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-24 15:00:00'}, {'dt': 1787594400, 'main': {'temp': 20.22, 'feels_like': 19.84, 'temp_min': 19.29, 'temp_max': 20.22, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1014, 'humidity': 59, 'temp_kf': 0.93, 'dew_point': 11.96}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 81}, 'wind': {'speed': 1.52, 'deg': 69, 'gust': 1.76}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-24 18:00:00'}, {'dt': 1787605200, 'main': {'temp': 18.46, 'feels_like': 17.88, 'temp_min': 17.34, 'temp_max': 18.46, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1015, 'humidity': 58, 'temp_kf': 1.12, 'dew_point': 10.05}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 35}, 'wind': {'speed': 1.45, 'deg': 140, 'gust': 1.62}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-24 21:00:00'}, {'dt': 1787616000, 'main': {'temp': 14.49, 'feels_like': 13.61, 'temp_min': 14.49, 'temp_max': 14.49, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1014, 'humidity': 62, 'temp_kf': 0, 'dew_point': 8.65}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 7}, 'wind': {'speed': 1.83, 'deg': 77, 'gust': 2.74}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-25 00:00:00'}, {'dt': 1787626800, 'main': {'temp': 13.72, 'feels_like': 12.9, 'temp_min': 13.72, 'temp_max': 13.72, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1013, 'humidity': 67, 'temp_kf': 0, 'dew_point': 8.87}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 2.05, 'deg': 68, 'gust': 3.68}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-25 03:00:00'}, {'dt': 1787637600, 'main': {'temp': 16.58, 'feels_like': 15.96, 'temp_min': 16.58, 'temp_max': 16.58, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1014, 'humidity': 64, 'temp_kf': 0, 'dew_point': 9.37}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 2.82, 'deg': 82, 'gust': 5.19}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-25 06:00:00'}, {'dt': 1787648400, 'main': {'temp': 22.01, 'feels_like': 21.36, 'temp_min': 22.01, 'temp_max': 22.01, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1014, 'humidity': 42, 'temp_kf': 0, 'dew_point': 8.38}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.08, 'deg': 86, 'gust': 6.32}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-25 09:00:00'}, {'dt': 1787659200, 'main': {'temp': 25, 'feels_like': 24.37, 'temp_min': 25, 'temp_max': 25, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1013, 'humidity': 31, 'temp_kf': 0, 'dew_point': 6.6}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 1}, 'wind': {'speed': 4.21, 'deg': 96, 'gust': 4.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-25 12:00:00'}, {'dt': 1787670000, 'main': {'temp': 25.35, 'feels_like': 24.7, 'temp_min': 25.35, 'temp_max': 25.35, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1012, 'humidity': 29, 'temp_kf': 0, 'dew_point': 5.74}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 1}, 'wind': {'speed': 4.41, 'deg': 96, 'gust': 4.91}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-25 15:00:00'}, {'dt': 1787680800, 'main': {'temp': 21.54, 'feels_like': 20.74, 'temp_min': 21.54, 'temp_max': 21.54, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1013, 'humidity': 38, 'temp_kf': 0, 'dew_point': 7.17}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 6}, 'wind': {'speed': 3.05, 'deg': 115, 'gust': 6.82}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-25 18:00:00'}, {'dt': 1787691600, 'main': {'temp': 18.38, 'feels_like': 17.55, 'temp_min': 18.38, 'temp_max': 18.38, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1014, 'humidity': 49, 'temp_kf': 0, 'dew_point': 8.24}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 13}, 'wind': {'speed': 3.12, 'deg': 107, 'gust': 9.24}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-25 21:00:00'}, {'dt': 1787702400, 'main': {'temp': 16.73, 'feels_like': 15.84, 'temp_min': 16.73, 'temp_max': 16.73, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1015, 'humidity': 53, 'temp_kf': 0, 'dew_point': 7.71}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 7}, 'wind': {'speed': 3.16, 'deg': 89, 'gust': 9.07}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-26 00:00:00'}, {'dt': 1787713200, 'main': {'temp': 15.4, 'feels_like': 14.46, 'temp_min': 15.4, 'temp_max': 15.4, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1015, 'humidity': 56, 'temp_kf': 0, 'dew_point': 7.19}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 3.77, 'deg': 93, 'gust': 10.39}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-26 03:00:00'}, {'dt': 1787724000, 'main': {'temp': 17.18, 'feels_like': 16.55, 'temp_min': 17.18, 'temp_max': 17.18, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1016, 'humidity': 61, 'temp_kf': 0, 'dew_point': 9.03}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.51, 'deg': 96, 'gust': 9.93}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-26 06:00:00'}, {'dt': 1787734800, 'main': {'temp': 22.19, 'feels_like': 21.54, 'temp_min': 22.19, 'temp_max': 22.19, 'pressure': 1022, 'sea_level': 1022, 'grnd_level': 1016, 'humidity': 41, 'temp_kf': 0, 'dew_point': 8.42}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 17}, 'wind': {'speed': 5.25, 'deg': 104, 'gust': 7.55}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-26 09:00:00'}, {'dt': 1787745600, 'main': {'temp': 25.06, 'feels_like': 24.43, 'temp_min': 25.06, 'temp_max': 25.06, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1015, 'humidity': 31, 'temp_kf': 0, 'dew_point': 6.78}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 36}, 'wind': {'speed': 4.85, 'deg': 112, 'gust': 5.64}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-26 12:00:00'}, {'dt': 1787756400, 'main': {'temp': 25.23, 'feels_like': 24.62, 'temp_min': 25.23, 'temp_max': 25.23, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1014, 'humidity': 31, 'temp_kf': 0, 'dew_point': 6.95}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 4.63, 'deg': 111, 'gust': 5.32}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-26 15:00:00'}, {'dt': 1787767200, 'main': {'temp': 22.89, 'feels_like': 22.25, 'temp_min': 22.89, 'temp_max': 22.89, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1014, 'humidity': 39, 'temp_kf': 0, 'dew_point': 8.26}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 3.59, 'deg': 102, 'gust': 6.87}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-26 18:00:00'}, {'dt': 1787778000, 'main': {'temp': 20.67, 'feels_like': 19.99, 'temp_min': 20.67, 'temp_max': 20.67, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1014, 'humidity': 46, 'temp_kf': 0, 'dew_point': 8.59}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 95}, 'wind': {'speed': 4.72, 'deg': 103, 'gust': 10.97}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-26 21:00:00'}, {'dt': 1787788800, 'main': {'temp': 19.31, 'feels_like': 18.58, 'temp_min': 19.31, 'temp_max': 19.31, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1014, 'humidity': 49, 'temp_kf': 0, 'dew_point': 8.29}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 91}, 'wind': {'speed': 5.2, 'deg': 103, 'gust': 13.44}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-27 00:00:00'}, {'dt': 1787799600, 'main': {'temp': 18.09, 'feels_like': 17.34, 'temp_min': 18.09, 'temp_max': 18.09, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1013, 'humidity': 53, 'temp_kf': 0, 'dew_point': 8.34}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.49, 'deg': 97, 'gust': 10.17}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-27 03:00:00'}, {'dt': 1787810400, 'main': {'temp': 18.11, 'feels_like': 17.41, 'temp_min': 18.11, 'temp_max': 18.11, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1013, 'humidity': 55, 'temp_kf': 0, 'dew_point': 8.9}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.82, 'deg': 106, 'gust': 10.98}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-27 06:00:00'}, {'dt': 1787821200, 'main': {'temp': 24.55, 'feels_like': 23.95, 'temp_min': 24.55, 'temp_max': 24.55, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1012, 'humidity': 34, 'temp_kf': 0, 'dew_point': 7.91}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 81}, 'wind': {'speed': 6.33, 'deg': 123, 'gust': 9.36}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-27 09:00:00'}, {'dt': 1787832000, 'main': {'temp': 28.04, 'feels_like': 27.04, 'temp_min': 28.04, 'temp_max': 28.04, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1011, 'humidity': 28, 'temp_kf': 0, 'dew_point': 7.72}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 66}, 'wind': {'speed': 6.32, 'deg': 125, 'gust': 7.7}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-27 12:00:00'}, {'dt': 1787842800, 'main': {'temp': 28.23, 'feels_like': 27.17, 'temp_min': 28.23, 'temp_max': 28.23, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1011, 'humidity': 28, 'temp_kf': 0, 'dew_point': 8.05}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 70}, 'wind': {'speed': 5.97, 'deg': 126, 'gust': 7.26}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-27 15:00:00'}, {'dt': 1787853600, 'main': {'temp': 24.82, 'feels_like': 24.32, 'temp_min': 24.82, 'temp_max': 24.82, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1009, 'humidity': 37, 'temp_kf': 0, 'dew_point': 9.03}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 83}, 'wind': {'speed': 4.95, 'deg': 113, 'gust': 10.07}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-27 18:00:00'}, {'dt': 1787864400, 'main': {'temp': 22.36, 'feels_like': 21.77, 'temp_min': 22.36, 'temp_max': 22.36, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1008, 'humidity': 43, 'temp_kf': 0, 'dew_point': 9.09}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.98, 'deg': 109, 'gust': 12.94}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-27 21:00:00'}, {'dt': 1787875200, 'main': {'temp': 20.84, 'feels_like': 20.26, 'temp_min': 20.84, 'temp_max': 20.84, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1007, 'humidity': 49, 'temp_kf': 0, 'dew_point': 9.62}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.18, 'deg': 104, 'gust': 13.41}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-28 00:00:00'}, {'dt': 1787886000, 'main': {'temp': 19.84, 'feels_like': 19.24, 'temp_min': 19.84, 'temp_max': 19.84, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1004, 'humidity': 52, 'temp_kf': 0, 'dew_point': 9.66}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 98}, 'wind': {'speed': 5.12, 'deg': 103, 'gust': 13.06}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-28 03:00:00'}, {'dt': 1787896800, 'main': {'temp': 19.94, 'feels_like': 19.3, 'temp_min': 19.94, 'temp_max': 19.94, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1006, 'humidity': 50, 'temp_kf': 0, 'dew_point': 9.4}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 96}, 'wind': {'speed': 3.67, 'deg': 156, 'gust': 10.55}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-28 06:00:00'}, {'dt': 1787907600, 'main': {'temp': 24.4, 'feels_like': 24.04, 'temp_min': 24.4, 'temp_max': 24.4, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1004, 'humidity': 44, 'temp_kf': 0, 'dew_point': 11.53}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.85, 'deg': 183, 'gust': 6.15}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-28 09:00:00'}, {'dt': 1787918400, 'main': {'temp': 26.36, 'feels_like': 26.36, 'temp_min': 26.36, 'temp_max': 26.36, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1004, 'humidity': 55, 'temp_kf': 0, 'dew_point': 16.6}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.21, 'deg': 226, 'gust': 6.09}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-28 12:00:00'}, {'dt': 1787929200, 'main': {'temp': 27.09, 'feels_like': 27.63, 'temp_min': 27.09, 'temp_max': 27.09, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1003, 'humidity': 52, 'temp_kf': 0, 'dew_point': 16.48}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.94, 'deg': 187, 'gust': 3.25}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-28 15:00:00'}, {'dt': 1787940000, 'main': {'temp': 24.36, 'feels_like': 24.44, 'temp_min': 24.36, 'temp_max': 24.36, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 61, 'temp_kf': 0, 'dew_point': 16.45}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 0.95, 'deg': 182, 'gust': 1.46}, 'visibility': 10000, 'pop': 0.31, 'rain': {'3h': 0.25}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-28 18:00:00'}, {'dt': 1787950800, 'main': {'temp': 20.37, 'feels_like': 20.68, 'temp_min': 20.37, 'temp_max': 20.37, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1004, 'humidity': 85, 'temp_kf': 0, 'dew_point': 17.65}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.21, 'deg': 237, 'gust': 7.79}, 'visibility': 8984, 'pop': 1, 'rain': {'3h': 6.4}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-28 21:00:00'}, {'dt': 1787961600, 'main': {'temp': 18.35, 'feels_like': 18.7, 'temp_min': 18.35, 'temp_max': 18.35, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 94, 'temp_kf': 0, 'dew_point': 17.41}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.46, 'deg': 273, 'gust': 6.59}, 'visibility': 6565, 'pop': 1, 'rain': {'3h': 6.22}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-29 00:00:00'}, {'dt': 1787972400, 'main': {'temp': 17.5, 'feels_like': 17.6, 'temp_min': 17.5, 'temp_max': 17.5, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1002, 'humidity': 88, 'temp_kf': 0, 'dew_point': 15.43}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.03, 'deg': 270, 'gust': 12.02}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 7.42}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-08-29 03:00:00'}, {'dt': 1787983200, 'main': {'temp': 17.55, 'feels_like': 17.61, 'temp_min': 17.55, 'temp_max': 17.55, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 86, 'temp_kf': 0, 'dew_point': 15.15}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.67, 'deg': 256, 'gust': 9.07}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 2.02}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-29 06:00:00'}, {'dt': 1787994000, 'main': {'temp': 19.11, 'feels_like': 19.03, 'temp_min': 19.11, 'temp_max': 19.11, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1004, 'humidity': 75, 'temp_kf': 0, 'dew_point': 14.46}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 55}, 'wind': {'speed': 6.42, 'deg': 271, 'gust': 10.47}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 1.08}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-29 09:00:00'}, {'dt': 1788004800, 'main': {'temp': 20.76, 'feels_like': 20.59, 'temp_min': 20.76, 'temp_max': 20.76, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1005, 'humidity': 65, 'temp_kf': 0, 'dew_point': 14.04}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 50}, 'wind': {'speed': 4.65, 'deg': 280, 'gust': 7.04}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 1.86}, 'sys': {'pod': 'd'}, 'dt_txt': '2026-08-29 12:00:00'}], 'city': {'id': 7576815, 'name': 'Alt-Kölln', 'coord': {'lat': 52.52, 'lon': 13.405}, 'country': 'DE', 'population': 2000, 'timezone': 7200, 'sunrise': 1787544222, 'sunset': 1787595260}}

## One city, one forecast

Start small by calling the API on a single location and exploring the returned data for one time

In [19]:
# select one row of cities_df
berlin = cities_df.loc[0]

url = "https://api.openweathermap.org/data/2.5/forecast"
params = {"lat": berlin["latitude"], "lon" :berlin["longitude"], "appid":openweather_key}

response = requests.get(url, params=params)
response

A response code of `200` means a successful request! Let's start exploring.

In [20]:
# transform output, check keys
response_json = response.json()
response_json.keys()

dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

Let's go through the keys one at time to understand the data structure

In [21]:
# looks like the status code
response_json['cod']

'200'

In [22]:
# ???
response_json['message']

0

In [23]:
# one forecast every 3 hours means 8 per day; five days times 8 makes 40 forecasts
response_json['cnt']

40

In [24]:
# looks like the forecasts themselves
response_json['list']

[{'dt': 1787583600,
  'main': {'temp': 293.85,
   'feels_like': 293.62,
   'temp_min': 293.85,
   'temp_max': 295.4,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1016,
   'humidity': 63,
   'temp_kf': -1.55,
   'dew_point': 286.56},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 95},
  'wind': {'speed': 1.43, 'deg': 307, 'gust': 1.68},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-24 15:00:00'},
 {'dt': 1787594400,
  'main': {'temp': 293.38,
   'feels_like': 293,
   'temp_min': 292.44,
   'temp_max': 293.38,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1014,
   'humidity': 59,
   'temp_kf': 0.94,
   'dew_point': 285.12},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 81},
  'wind': {'speed': 1.52, 'deg': 69, 'gust': 1.76},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-24 18:00:00'},
 {'dt': 1787605200,
  'main': {'temp': 291.61,
   'feels_like': 291.03,
   'temp_min': 290.49,
   'temp_max': 291.61,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1015,
   'humidity': 58,
   'temp_kf': 1.12,
   'dew_point': 283.2},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 35},
  'wind': {'speed': 1.45, 'deg': 140, 'gust': 1.62},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-24 21:00:00'},
 {'dt': 1787616000,
  'main': {'temp': 287.64,
   'feels_like': 286.76,
   'temp_min': 287.64,
   'temp_max': 287.64,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1014,
   'humidity': 62,
   'temp_kf': 0,
   'dew_point': 281.8},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 7},
  'wind': {'speed': 1.83, 'deg': 77, 'gust': 2.74},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-25 00:00:00'},
 {'dt': 1787626800,
  'main': {'temp': 286.87,
   'feels_like': 286.05,
   'temp_min': 286.87,
   'temp_max': 286.87,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1013,
   'humidity': 67,
   'temp_kf': 0,
   'dew_point': 282.02},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 0},
  'wind': {'speed': 2.05, 'deg': 68, 'gust': 3.68},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-25 03:00:00'},
 {'dt': 1787637600,
  'main': {'temp': 289.73,
   'feels_like': 289.11,
   'temp_min': 289.73,
   'temp_max': 289.73,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1014,
   'humidity': 64,
   'temp_kf': 0,
   'dew_point': 282.52},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 0},
  'wind': {'speed': 2.82, 'deg': 82, 'gust': 5.19},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-25 06:00:00'},
 {'dt': 1787648400,
  'main': {'temp': 295.16,
   'feels_like': 294.51,
   'temp_min': 295.16,
   'temp_max': 295.16,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1014,
   'humidity': 42,
   'temp_kf': 0,
   'dew_point': 281.53},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 0},
  'wind': {'speed': 4.08, 'deg': 86, 'gust': 6.32},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-25 09:00:00'},
 {'dt': 1787659200,
  'main': {'temp': 298.15,
   'feels_like': 297.52,
   'temp_min': 298.15,
   'temp_max': 298.15,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 1013,
   'humidity': 31,
   'temp_kf': 0,
   'dew_point': 279.75},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 1},
  'wind': {'speed': 4.21, 'deg': 96, 'gust': 4.92},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-25 12:00:00'},
 {'dt': 1787670000,
  'main': {'temp': 298.5,
   'feels_like': 297.85,
   'temp_min': 298.5,
   'temp_max': 298.5,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 1012,
   'humidity': 29,
   'temp_kf': 0,
   'dew_point': 278.89},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 1},
  'wind': {'speed': 4.41, 'deg': 96, 'gust': 4.91},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-25 15:00:00'},
 {'dt': 1787680800,
  'main': {'temp': 294.69,
   'feels_like': 293.89,
   'temp_min': 294.69,
   'temp_max': 294.69,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 1013,
   'humidity': 38,
   'temp_kf': 0,
   'dew_point': 280.32},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 6},
  'wind': {'speed': 3.05, 'deg': 115, 'gust': 6.82},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-25 18:00:00'},
 {'dt': 1787691600,
  'main': {'temp': 291.53,
   'feels_like': 290.7,
   'temp_min': 291.53,
   'temp_max': 291.53,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1014,
   'humidity': 49,
   'temp_kf': 0,
   'dew_point': 281.39},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 13},
  'wind': {'speed': 3.12, 'deg': 107, 'gust': 9.24},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-25 21:00:00'},
 {'dt': 1787702400,
  'main': {'temp': 289.88,
   'feels_like': 288.99,
   'temp_min': 289.88,
   'temp_max': 289.88,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1015,
   'humidity': 53,
   'temp_kf': 0,
   'dew_point': 280.86},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 7},
  'wind': {'speed': 3.16, 'deg': 89, 'gust': 9.07},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-26 00:00:00'},
 {'dt': 1787713200,
  'main': {'temp': 288.55,
   'feels_like': 287.61,
   'temp_min': 288.55,
   'temp_max': 288.55,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1015,
   'humidity': 56,
   'temp_kf': 0,
   'dew_point': 280.34},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 0},
  'wind': {'speed': 3.77, 'deg': 93, 'gust': 10.39},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-26 03:00:00'},
 {'dt': 1787724000,
  'main': {'temp': 290.33,
   'feels_like': 289.7,
   'temp_min': 290.33,
   'temp_max': 290.33,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1016,
   'humidity': 61,
   'temp_kf': 0,
   'dew_point': 282.18},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 0},
  'wind': {'speed': 4.51, 'deg': 96, 'gust': 9.93},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-26 06:00:00'},
 {'dt': 1787734800,
  'main': {'temp': 295.34,
   'feels_like': 294.69,
   'temp_min': 295.34,
   'temp_max': 295.34,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1016,
   'humidity': 41,
   'temp_kf': 0,
   'dew_point': 281.57},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 17},
  'wind': {'speed': 5.25, 'deg': 104, 'gust': 7.55},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-26 09:00:00'},
 {'dt': 1787745600,
  'main': {'temp': 298.21,
   'feels_like': 297.58,
   'temp_min': 298.21,
   'temp_max': 298.21,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1015,
   'humidity': 31,
   'temp_kf': 0,
   'dew_point': 279.93},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 36},
  'wind': {'speed': 4.85, 'deg': 112, 'gust': 5.64},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-26 12:00:00'},
 {'dt': 1787756400,
  'main': {'temp': 298.38,
   'feels_like': 297.77,
   'temp_min': 298.38,
   'temp_max': 298.38,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1014,
   'humidity': 31,
   'temp_kf': 0,
   'dew_point': 280.1},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 99},
  'wind': {'speed': 4.63, 'deg': 111, 'gust': 5.32},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-26 15:00:00'},
 {'dt': 1787767200,
  'main': {'temp': 296.04,
   'feels_like': 295.4,
   'temp_min': 296.04,
   'temp_max': 296.04,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1014,
   'humidity': 39,
   'temp_kf': 0,
   'dew_point': 281.41},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 99},
  'wind': {'speed': 3.59, 'deg': 102, 'gust': 6.87},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-26 18:00:00'},
 {'dt': 1787778000,
  'main': {'temp': 293.82,
   'feels_like': 293.14,
   'temp_min': 293.82,
   'temp_max': 293.82,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1014,
   'humidity': 46,
   'temp_kf': 0,
   'dew_point': 281.74},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 95},
  'wind': {'speed': 4.72, 'deg': 103, 'gust': 10.97},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-26 21:00:00'},
 {'dt': 1787788800,
  'main': {'temp': 292.46,
   'feels_like': 291.73,
   'temp_min': 292.46,
   'temp_max': 292.46,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1014,
   'humidity': 49,
   'temp_kf': 0,
   'dew_point': 281.44},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 91},
  'wind': {'speed': 5.2, 'deg': 103, 'gust': 13.44},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-27 00:00:00'},
 {'dt': 1787799600,
  'main': {'temp': 291.24,
   'feels_like': 290.49,
   'temp_min': 291.24,
   'temp_max': 291.24,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1013,
   'humidity': 53,
   'temp_kf': 0,
   'dew_point': 281.49},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.49, 'deg': 97, 'gust': 10.17},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-27 03:00:00'},
 {'dt': 1787810400,
  'main': {'temp': 291.26,
   'feels_like': 290.56,
   'temp_min': 291.26,
   'temp_max': 291.26,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 1013,
   'humidity': 55,
   'temp_kf': 0,
   'dew_point': 282.05},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.82, 'deg': 106, 'gust': 10.98},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-27 06:00:00'},
 {'dt': 1787821200,
  'main': {'temp': 297.7,
   'feels_like': 297.1,
   'temp_min': 297.7,
   'temp_max': 297.7,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 1012,
   'humidity': 34,
   'temp_kf': 0,
   'dew_point': 281.06},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 81},
  'wind': {'speed': 6.33, 'deg': 123, 'gust': 9.36},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-27 09:00:00'},
 {'dt': 1787832000,
  'main': {'temp': 301.19,
   'feels_like': 300.19,
   'temp_min': 301.19,
   'temp_max': 301.19,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1011,
   'humidity': 28,
   'temp_kf': 0,
   'dew_point': 280.87},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 66},
  'wind': {'speed': 6.32, 'deg': 125, 'gust': 7.7},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-27 12:00:00'},
 {'dt': 1787842800,
  'main': {'temp': 301.38,
   'feels_like': 300.32,
   'temp_min': 301.38,
   'temp_max': 301.38,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1011,
   'humidity': 28,
   'temp_kf': 0,
   'dew_point': 281.2},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 70},
  'wind': {'speed': 5.97, 'deg': 126, 'gust': 7.26},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-27 15:00:00'},
 {'dt': 1787853600,
  'main': {'temp': 297.97,
   'feels_like': 297.47,
   'temp_min': 297.97,
   'temp_max': 297.97,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1009,
   'humidity': 37,
   'temp_kf': 0,
   'dew_point': 282.18},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 83},
  'wind': {'speed': 4.95, 'deg': 113, 'gust': 10.07},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-27 18:00:00'},
 {'dt': 1787864400,
  'main': {'temp': 295.51,
   'feels_like': 294.92,
   'temp_min': 295.51,
   'temp_max': 295.51,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1008,
   'humidity': 43,
   'temp_kf': 0,
   'dew_point': 282.24},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.98, 'deg': 109, 'gust': 12.94},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-27 21:00:00'},
 {'dt': 1787875200,
  'main': {'temp': 293.99,
   'feels_like': 293.41,
   'temp_min': 293.99,
   'temp_max': 293.99,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1007,
   'humidity': 49,
   'temp_kf': 0,
   'dew_point': 282.77},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 5.18, 'deg': 104, 'gust': 13.41},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-28 00:00:00'},
 {'dt': 1787886000,
  'main': {'temp': 292.99,
   'feels_like': 292.39,
   'temp_min': 292.99,
   'temp_max': 292.99,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 52,
   'temp_kf': 0,
   'dew_point': 282.81},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 98},
  'wind': {'speed': 5.12, 'deg': 103, 'gust': 13.06},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-28 03:00:00'},
 {'dt': 1787896800,
  'main': {'temp': 293.09,
   'feels_like': 292.45,
   'temp_min': 293.09,
   'temp_max': 293.09,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1006,
   'humidity': 50,
   'temp_kf': 0,
   'dew_point': 282.55},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 96},
  'wind': {'speed': 3.67, 'deg': 156, 'gust': 10.55},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-28 06:00:00'},
 {'dt': 1787907600,
  'main': {'temp': 297.55,
   'feels_like': 297.19,
   'temp_min': 297.55,
   'temp_max': 297.55,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 44,
   'temp_kf': 0,
   'dew_point': 284.68},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.85, 'deg': 183, 'gust': 6.15},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-28 09:00:00'},
 {'dt': 1787918400,
  'main': {'temp': 299.51,
   'feels_like': 299.51,
   'temp_min': 299.51,
   'temp_max': 299.51,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 55,
   'temp_kf': 0,
   'dew_point': 289.75},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.21, 'deg': 226, 'gust': 6.09},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-28 12:00:00'},
 {'dt': 1787929200,
  'main': {'temp': 300.24,
   'feels_like': 300.78,
   'temp_min': 300.24,
   'temp_max': 300.24,
   'pressure': 1009,
   'sea_level': 1009,
   'grnd_level': 1003,
   'humidity': 52,
   'temp_kf': 0,
   'dew_point': 289.63},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 1.94, 'deg': 187, 'gust': 3.25},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-28 15:00:00'},
 {'dt': 1787940000,
  'main': {'temp': 297.51,
   'feels_like': 297.59,
   'temp_min': 297.51,
   'temp_max': 297.51,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1003,
   'humidity': 61,
   'temp_kf': 0,
   'dew_point': 289.6},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 0.95, 'deg': 182, 'gust': 1.46},
  'visibility': 10000,
  'pop': 0.31,
  'rain': {'3h': 0.25},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-28 18:00:00'},
 {'dt': 1787950800,
  'main': {'temp': 293.52,
   'feels_like': 293.83,
   'temp_min': 293.52,
   'temp_max': 293.52,
   'pressure': 1009,
   'sea_level': 1009,
   'grnd_level': 1004,
   'humidity': 85,
   'temp_kf': 0,
   'dew_point': 290.8},
  'weather': [{'id': 501,
    'main': 'Rain',
    'description': 'moderate rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.21, 'deg': 237, 'gust': 7.79},
  'visibility': 8984,
  'pop': 1,
  'rain': {'3h': 6.4},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-28 21:00:00'},
 {'dt': 1787961600,
  'main': {'temp': 291.5,
   'feels_like': 291.85,
   'temp_min': 291.5,
   'temp_max': 291.5,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1003,
   'humidity': 94,
   'temp_kf': 0,
   'dew_point': 290.56},
  'weather': [{'id': 501,
    'main': 'Rain',
    'description': 'moderate rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.46, 'deg': 273, 'gust': 6.59},
  'visibility': 6565,
  'pop': 1,
  'rain': {'3h': 6.22},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-29 00:00:00'},
 {'dt': 1787972400,
  'main': {'temp': 290.65,
   'feels_like': 290.75,
   'temp_min': 290.65,
   'temp_max': 290.65,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1002,
   'humidity': 88,
   'temp_kf': 0,
   'dew_point': 288.58},
  'weather': [{'id': 501,
    'main': 'Rain',
    'description': 'moderate rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 5.03, 'deg': 270, 'gust': 12.02},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 7.42},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-08-29 03:00:00'},
 {'dt': 1787983200,
  'main': {'temp': 290.7,
   'feels_like': 290.76,
   'temp_min': 290.7,
   'temp_max': 290.7,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1003,
   'humidity': 86,
   'temp_kf': 0,
   'dew_point': 288.3},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.67, 'deg': 256, 'gust': 9.07},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 2.02},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-08-29 06:00:00'},
 {'dt': 1787994000,
  'main': {'temp': 292.26,
   'feels_like': 292.18,
   'temp_min': 292.26,

In [25]:
# matches 'cnt' above!
len(response_json['list'])

40

In [26]:
# we have this info in the 'cities' table
response_json['city']

{'id': 6545310,
 'name': 'Mitte',
 'coord': {'lat': 52.52, 'lon': 13.405},
 'country': 'DE',
 'population': 329078,
 'timezone': 7200,
 'sunrise': 1787544222,
 'sunset': 1787595260}

Time to explore one forecast and see what to keep.

In [27]:
forecast = response_json['list'][0]
forecast

{'dt': 1787583600,
 'main': {'temp': 293.85,
  'feels_like': 293.62,
  'temp_min': 293.85,
  'temp_max': 295.4,
  'pressure': 1021,
  'sea_level': 1021,
  'grnd_level': 1016,
  'humidity': 63,
  'temp_kf': -1.55,
  'dew_point': 286.56},
 'weather': [{'id': 804,
   'main': 'Clouds',
   'description': 'overcast clouds',
   'icon': '04d'}],
 'clouds': {'all': 95},
 'wind': {'speed': 1.43, 'deg': 307, 'gust': 1.68},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'd'},
 'dt_txt': '2026-08-24 15:00:00'}

* dt looks like some kind of timestamp
* main
    * temp looks crazy! 292 degrees!  (use units=metric instead)
    * feels_like might be more important for people than the actual temperature
    * temp_min/max might be worth keeping? maybe not
    * humidity might affect if people rent scooters or not
* weather looks like the kind of descriptions a weather app would show
* clouds probably not needed
* wind
    * speed or gust could be important
* visibility probably not needed
* pop 'probability of precipitation' seems useful
* rain and snow seem useful
* sys probably not needed
* dt_txt a much better timestamp

In [28]:
forecast['wind']#["feels_like"]

{'speed': 1.43, 'deg': 307, 'gust': 1.68}

In [29]:
forecast_data = {
    "temp": forecast['main']['temp'],
    "feels_like": forecast['main']['feels_like'],
    "humidity_%": forecast['main']['humidity'],
    "wind_speed": forecast['wind']['speed'],
    "wind_gust": forecast['wind']['gust'],
    "precipitation_%": forecast['pop'],
    # # docs say there's 'rain' and 'snow', but it's not here!
    "forecast_time": forecast['dt_txt']
}
forecast_data

{'temp': 293.85,
 'feels_like': 293.62,
 'humidity_%': 63,
 'wind_speed': 1.43,
 'wind_gust': 1.68,
 'precipitation_%': 0,
 'forecast_time': '2026-08-24 15:00:00'}

## One city, all forecasts

Now that we have useful information from one forecast, let's try to extract the same information from the other 39, too.

In [42]:
forecasts = []
for forecast in response_json['list']:
    forecast_data = {
        "temp": forecast['main']['temp'],
        "feels_like": forecast['main']['feels_like'],
        "humidity_%": forecast['main']['humidity'],
        "wind_speed": forecast['wind']['speed'],
        "wind_gust": forecast['wind']['gust'],
        "precipitation_%": forecast['pop'],
        "rain_3h": forecast.get('rain', {}).get('3h', 0),
        "snow_3h": forecast.get('snow', {}).get('3h', 0),
        # docs say there's 'snow', but it's not here!
        "forecast_time": forecast['dt_txt']
    }
    forecasts.append(forecast_data)
forecasts

[{'temp': 25,
  'feels_like': 24.76,
  'humidity_%': 46,
  'wind_speed': 4.41,
  'wind_gust': 4.8,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-24 15:00:00'},
 {'temp': 23.88,
  'feels_like': 23.68,
  'humidity_%': 52,
  'wind_speed': 3.23,
  'wind_gust': 8.4,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-24 18:00:00'},
 {'temp': 18.77,
  'feels_like': 18.45,
  'humidity_%': 67,
  'wind_speed': 3.26,
  'wind_gust': 11.07,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-24 21:00:00'},
 {'temp': 13.76,
  'feels_like': 13.12,
  'humidity_%': 74,
  'wind_speed': 2.91,
  'wind_gust': 8.82,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 00:00:00'},
 {'temp': 11.62,
  'feels_like': 11.19,
  'humidity_%': 90,
  'wind_speed': 1.32,
  'wind_gust': 2.27,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 03:00:00'},
 {'temp': 13.22,
  'feels_like': 13.1,
  'humidity_%': 96,
  'wind_speed': 1.18,
  'wind_gust': 3.64,
  'precipitation_%': 1,
  'rain_3h': 2.82,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 06:00:00'},
 {'temp': 17.59,
  'feels_like': 17.91,
  'humidity_%': 96,
  'wind_speed': 3.14,
  'wind_gust': 7.41,
  'precipitation_%': 1,
  'rain_3h': 2.45,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 09:00:00'},
 {'temp': 21.13,
  'feels_like': 21.34,
  'humidity_%': 78,
  'wind_speed': 1.47,
  'wind_gust': 2.62,
  'precipitation_%': 1,
  'rain_3h': 0.49,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 12:00:00'},
 {'temp': 24.38,
  'feels_like': 24.44,
  'humidity_%': 60,
  'wind_speed': 2.16,
  'wind_gust': 1.59,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 15:00:00'},
 {'temp': 20.66,
  'feels_like': 21.24,
  'humidity_%': 94,
  'wind_speed': 2.4,
  'wind_gust': 5.5,
  'precipitation_%': 0.99,
  'rain_3h': 1.16,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 18:00:00'},
 {'temp': 16.73,
  'feels_like': 16.99,
  'humidity_%': 97,
  'wind_speed': 1.32,
  'wind_gust': 1.41,
  'precipitation_%': 1,
  'rain_3h': 1.88,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 21:00:00'},
 {'temp': 15.77,
  'feels_like': 15.86,
  'humidity_%': 94,
  'wind_speed': 1.01,
  'wind_gust': 1.09,
  'precipitation_%': 0.8,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 00:00:00'},
 {'temp': 15.12,
  'feels_like': 15.12,
  'humidity_%': 93,
  'wind_speed': 1.27,
  'wind_gust': 1.22,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 03:00:00'},
 {'temp': 17.54,
  'feels_like': 17.75,
  'humidity_%': 92,
  'wind_speed': 1.49,
  'wind_gust': 2.87,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 06:00:00'},
 {'temp': 22.52,
  'feels_like': 22.39,
  'humidity_%': 60,
  'wind_speed': 1.64,
  'wind_gust': 1.53,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 09:00:00'},
 {'temp': 26.95,
  'feels_like': 27.03,
  'humidity_%': 44,
  'wind_speed': 1.58,
  'wind_gust': 1.22,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 12:00:00'},
 {'temp': 26.66,
  'feels_like': 26.66,
  'humidity_%': 46,
  'wind_speed': 2.47,
  'wind_gust': 2.3,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 15:00:00'},
 {'temp': 20.93,
  'feels_like': 20.96,
  'humidity_%': 72,
  'wind_speed': 2.53,
  'wind_gust': 6.88,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 18:00:00'},
 {'temp': 18.61,
  'feels_like': 18.62,
  'humidity_%': 80,
  'wind_speed': 2.22,
  'wind_gust': 3.74,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 21:00:00'},
 {'temp': 17.63,
  'feels_like': 17.62,
  'humidity_%': 83,
  'wind_speed': 1.12,
  'wind_gust': 0.82,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 00:00:00'},
 {'temp': 16.56,
  'feels_like': 16.49,
  'humidity_%': 85,
  'wind_speed': 2.06,
  'wind_gust': 2.72,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 03:00:00'},
 {'temp': 17.87,
  'feels_like': 17.72,
  'humidity_%': 77,
  'wind_speed': 1.71,
  'wind_gust': 4.03,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 06:00:00'},
 {'temp': 24.97,
  'feels_like': 24.88,
  'humidity_%': 52,
  'wind_speed': 2.94,
  'wind_gust': 3.94,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 09:00:00'},
 {'temp': 28.27,
  'feels_like': 28.3,
  'humidity_%': 45,
  'wind_speed': 3.07,
  'wind_gust': 3.41,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 12:00:00'},
 {'temp': 29.33,
  'feels_like': 29.26,
  'humidity_%': 43,
  'wind_speed': 3.51,
  'wind_gust': 4.3,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 15:00:00'},
 {'temp': 23.76,
  'feels_like': 23.89,
  'humidity_%': 65,
  'wind_speed': 3.49,
  'wind_gust': 10.74,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 18:00:00'},
 {'temp': 21,
  'feels_like': 21.24,
  'humidity_%': 80,
  'wind_speed': 2.77,
  'wind_gust': 7.66,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 21:00:00'},
 {'temp': 19.51,
  'feels_like': 19.45,
  'humidity_%': 74,
  'wind_speed': 1.96,
  'wind_gust': 2.81,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 00:00:00'},
 {'temp': 20.32,
  'feels_like': 20.1,
  'humidity_%': 65,
  'wind_speed': 4.63,
  'wind_gust': 16.74,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 03:00:00'},
 {'temp': 19.78,
  'feels_like': 19.98,
  'humidity_%': 83,
  'wind_speed': 3.48,
  'wind_gust': 6.97,
  'precipitation_%': 0.2,
  'rain_3h': 0.19,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 06:00:00'},
 {'temp': 24.32,
  'feels_like': 24.3,
  'humidity_%': 57,
  'wind_speed': 1.01,
  'wind_gust': 1.58,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 09:00:00'},
 {'temp': 27.32,
  'feels_like': 27.46,
  'humidity_%': 46,
  'wind_speed': 1.32,
  'wind_gust': 1.92,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 12:00:00'},
 {'temp': 18.84,
  'feels_like': 19.05,
  'humidity_%': 87,
  'wind_speed': 5.06,
  'wind_gust': 10.05,
  'precipitation_%': 0.69,
  'rain_3h': 0.41,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 15:00:00'},
 {'temp': 17.97,
  'feels_like': 18.36,
  'humidity_%': 97,
  'wind_speed': 2.49,
  'wind_gust': 4.59,
  'precipitation_%': 1,
  'rain_3h': 1.71,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 18:00:00'},
 {'temp': 14.56,
  'feels_like': 14.45,
  'humidity_%': 91,
  'wind_speed': 4.24,
  'wind_gust': 12.96,
  'precipitation_%': 1,
  'rain_3h': 15.43,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 21:00:00'},
 {'temp': 14.26,
  'feels_like': 14.2,
  'humidity_%': 94,
  'wind_speed': 3.08,
  'wind_gust': 10.92,
  'precipitation_%': 1,
  'rain_3h': 0.27,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 00:00:00'},
 {'temp': 13.84,
  'feels_like': 13.66,
  'humidity_%': 91,
  'wind_speed': 4.06,
  'wind_gust': 13.16,
  'precipitation_%': 0.34,
  'rain_3h': 0.16,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 03:00:00'},
 {'temp': 14.73,
  'feels_like': 14.43,
  'humidity_%': 83,
  'wind_speed': 4,
  'wind_gust': 12.2,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 06:00:00'},
 {'temp': 20.02,
  'feels_like': 19.44,
  'humidity_%': 52,
  'wind_speed': 6.4,
  'wind_gust': 10.26,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 09:00:00'},
 {'temp': 21.27,
  'feels_like': 20.78,
  'humidity_%': 51,
  'wind_speed': 6.62,
  'wind_gust': 10.25,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 12:00:00'}]

Oh no! One of the forecasts has no 'rain'!

In [31]:
forecast # the iteration variable stays stuck wherever the loop broke

{'dt': 1787583600,
 'main': {'temp': 293.85,
  'feels_like': 293.62,
  'temp_min': 293.85,
  'temp_max': 295.4,
  'pressure': 1021,
  'sea_level': 1021,
  'grnd_level': 1016,
  'humidity': 63,
  'temp_kf': -1.55,
  'dew_point': 286.56},
 'weather': [{'id': 804,
   'main': 'Clouds',
   'description': 'overcast clouds',
   'icon': '04d'}],
 'clouds': {'all': 95},
 'wind': {'speed': 1.43, 'deg': 307, 'gust': 1.68},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'd'},
 'dt_txt': '2026-08-24 15:00:00'}

Indeed, there's no 'rain' in this dictionary, just like we saw no 'snow' before. JSON documents are semi-structured; where there's no data, they might leave things out rather than listing a null value. Thankfully, python dictionaries have a method that allow us to retrieve a key that might not be there: `.get()`. We can even set the value to return if the key isn't found.

In [32]:
forecast.get('dt_txt')

'2026-08-24 15:00:00'

In [33]:
forecast.get('rain', {}) # {} is the default value

{}

By returning an empty dictionary as the default, we can chain more searches together.

In [34]:
# returns a reasonable value for "no rain in the last three hours"
forecast.get('rain', {}).get('3h', 0)

0

In [35]:
# works just fine if there has been rain
response_json['list'][11].get('rain', {}).get('3h', 0)

0

We'll adjust our loop to use `.get()`

In [36]:
forecasts = []
for forecast in response_json['list']:
    forecast_data = {
        "temp": forecast['main']['temp'],
        "feels_like": forecast['main']['feels_like'],
        "humidity_%": forecast['main']['humidity'],
        "wind_speed": forecast['wind']['speed'],
        "wind_gust": forecast['wind']['gust'],
        "precipitation_%": forecast['pop'],
        "rain_3h": forecast.get('rain', {}).get('3h', 0),
        "snow_3h": forecast.get('snow', {}).get('3h', 0),
        "forecast_time": forecast['dt_txt']
    }
    forecasts.append(forecast_data)
forecasts

[{'temp': 293.85,
  'feels_like': 293.62,
  'humidity_%': 63,
  'wind_speed': 1.43,
  'wind_gust': 1.68,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-24 15:00:00'},
 {'temp': 293.38,
  'feels_like': 293,
  'humidity_%': 59,
  'wind_speed': 1.52,
  'wind_gust': 1.76,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-24 18:00:00'},
 {'temp': 291.61,
  'feels_like': 291.03,
  'humidity_%': 58,
  'wind_speed': 1.45,
  'wind_gust': 1.62,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-24 21:00:00'},
 {'temp': 287.64,
  'feels_like': 286.76,
  'humidity_%': 62,
  'wind_speed': 1.83,
  'wind_gust': 2.74,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 00:00:00'},
 {'temp': 286.87,
  'feels_like': 286.05,
  'humidity_%': 67,
  'wind_speed': 2.05,
  'wind_gust': 3.68,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 03:00:00'},
 {'temp': 289.73,
  'feels_like': 289.11,
  'humidity_%': 64,
  'wind_speed': 2.82,
  'wind_gust': 5.19,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 06:00:00'},
 {'temp': 295.16,
  'feels_like': 294.51,
  'humidity_%': 42,
  'wind_speed': 4.08,
  'wind_gust': 6.32,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 09:00:00'},
 {'temp': 298.15,
  'feels_like': 297.52,
  'humidity_%': 31,
  'wind_speed': 4.21,
  'wind_gust': 4.92,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 12:00:00'},
 {'temp': 298.5,
  'feels_like': 297.85,
  'humidity_%': 29,
  'wind_speed': 4.41,
  'wind_gust': 4.91,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 15:00:00'},
 {'temp': 294.69,
  'feels_like': 293.89,
  'humidity_%': 38,
  'wind_speed': 3.05,
  'wind_gust': 6.82,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 18:00:00'},
 {'temp': 291.53,
  'feels_like': 290.7,
  'humidity_%': 49,
  'wind_speed': 3.12,
  'wind_gust': 9.24,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-25 21:00:00'},
 {'temp': 289.88,
  'feels_like': 288.99,
  'humidity_%': 53,
  'wind_speed': 3.16,
  'wind_gust': 9.07,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 00:00:00'},
 {'temp': 288.55,
  'feels_like': 287.61,
  'humidity_%': 56,
  'wind_speed': 3.77,
  'wind_gust': 10.39,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 03:00:00'},
 {'temp': 290.33,
  'feels_like': 289.7,
  'humidity_%': 61,
  'wind_speed': 4.51,
  'wind_gust': 9.93,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 06:00:00'},
 {'temp': 295.34,
  'feels_like': 294.69,
  'humidity_%': 41,
  'wind_speed': 5.25,
  'wind_gust': 7.55,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 09:00:00'},
 {'temp': 298.21,
  'feels_like': 297.58,
  'humidity_%': 31,
  'wind_speed': 4.85,
  'wind_gust': 5.64,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 12:00:00'},
 {'temp': 298.38,
  'feels_like': 297.77,
  'humidity_%': 31,
  'wind_speed': 4.63,
  'wind_gust': 5.32,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 15:00:00'},
 {'temp': 296.04,
  'feels_like': 295.4,
  'humidity_%': 39,
  'wind_speed': 3.59,
  'wind_gust': 6.87,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 18:00:00'},
 {'temp': 293.82,
  'feels_like': 293.14,
  'humidity_%': 46,
  'wind_speed': 4.72,
  'wind_gust': 10.97,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-26 21:00:00'},
 {'temp': 292.46,
  'feels_like': 291.73,
  'humidity_%': 49,
  'wind_speed': 5.2,
  'wind_gust': 13.44,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 00:00:00'},
 {'temp': 291.24,
  'feels_like': 290.49,
  'humidity_%': 53,
  'wind_speed': 4.49,
  'wind_gust': 10.17,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 03:00:00'},
 {'temp': 291.26,
  'feels_like': 290.56,
  'humidity_%': 55,
  'wind_speed': 4.82,
  'wind_gust': 10.98,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 06:00:00'},
 {'temp': 297.7,
  'feels_like': 297.1,
  'humidity_%': 34,
  'wind_speed': 6.33,
  'wind_gust': 9.36,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 09:00:00'},
 {'temp': 301.19,
  'feels_like': 300.19,
  'humidity_%': 28,
  'wind_speed': 6.32,
  'wind_gust': 7.7,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 12:00:00'},
 {'temp': 301.38,
  'feels_like': 300.32,
  'humidity_%': 28,
  'wind_speed': 5.97,
  'wind_gust': 7.26,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 15:00:00'},
 {'temp': 297.97,
  'feels_like': 297.47,
  'humidity_%': 37,
  'wind_speed': 4.95,
  'wind_gust': 10.07,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 18:00:00'},
 {'temp': 295.51,
  'feels_like': 294.92,
  'humidity_%': 43,
  'wind_speed': 4.98,
  'wind_gust': 12.94,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-27 21:00:00'},
 {'temp': 293.99,
  'feels_like': 293.41,
  'humidity_%': 49,
  'wind_speed': 5.18,
  'wind_gust': 13.41,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 00:00:00'},
 {'temp': 292.99,
  'feels_like': 292.39,
  'humidity_%': 52,
  'wind_speed': 5.12,
  'wind_gust': 13.06,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 03:00:00'},
 {'temp': 293.09,
  'feels_like': 292.45,
  'humidity_%': 50,
  'wind_speed': 3.67,
  'wind_gust': 10.55,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 06:00:00'},
 {'temp': 297.55,
  'feels_like': 297.19,
  'humidity_%': 44,
  'wind_speed': 3.85,
  'wind_gust': 6.15,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 09:00:00'},
 {'temp': 299.51,
  'feels_like': 299.51,
  'humidity_%': 55,
  'wind_speed': 4.21,
  'wind_gust': 6.09,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 12:00:00'},
 {'temp': 300.24,
  'feels_like': 300.78,
  'humidity_%': 52,
  'wind_speed': 1.94,
  'wind_gust': 3.25,
  'precipitation_%': 0,
  'rain_3h': 0,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 15:00:00'},
 {'temp': 297.51,
  'feels_like': 297.59,
  'humidity_%': 61,
  'wind_speed': 0.95,
  'wind_gust': 1.46,
  'precipitation_%': 0.31,
  'rain_3h': 0.25,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 18:00:00'},
 {'temp': 293.52,
  'feels_like': 293.83,
  'humidity_%': 85,
  'wind_speed': 4.21,
  'wind_gust': 7.79,
  'precipitation_%': 1,
  'rain_3h': 6.4,
  'snow_3h': 0,
  'forecast_time': '2026-08-28 21:00:00'},
 {'temp': 291.5,
  'feels_like': 291.85,
  'humidity_%': 94,
  'wind_speed': 3.46,
  'wind_gust': 6.59,
  'precipitation_%': 1,
  'rain_3h': 6.22,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 00:00:00'},
 {'temp': 290.65,
  'feels_like': 290.75,
  'humidity_%': 88,
  'wind_speed': 5.03,
  'wind_gust': 12.02,
  'precipitation_%': 1,
  'rain_3h': 7.42,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 03:00:00'},
 {'temp': 290.7,
  'feels_like': 290.76,
  'humidity_%': 86,
  'wind_speed': 4.67,
  'wind_gust': 9.07,
  'precipitation_%': 1,
  'rain_3h': 2.02,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 06:00:00'},
 {'temp': 292.26,
  'feels_like': 292.18,
  'humidity_%': 75,
  'wind_speed': 6.42,
  'wind_gust': 10.47,
  'precipitation_%': 1,
  'rain_3h': 1.08,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 09:00:00'},
 {'temp': 293.91,
  'feels_like': 293.74,
  'humidity_%': 65,
  'wind_speed': 4.65,
  'wind_gust': 7.04,
  'precipitation_%': 1,
  'rain_3h': 1.86,
  'snow_3h': 0,
  'forecast_time': '2026-08-29 12:00:00'}]

In [37]:
pd.DataFrame(forecasts)

,temp,feels_like,humidity_%,wind_speed,wind_gust,precipitation_%,rain_3h,snow_3h,forecast_time
0,293.85,293.62,63,1.43,1.68,0.00,0.00,0,2026-08-24 15:00:00
1,293.38,293.00,59,1.52,1.76,0.00,0.00,0,2026-08-24 18:00:00
2,291.61,291.03,58,1.45,1.62,0.00,0.00,0,2026-08-24 21:00:00
3,287.64,286.76,62,1.83,2.74,0.00,0.00,0,2026-08-25 00:00:00
4,286.87,286.05,67,2.05,3.68,0.00,0.00,0,2026-08-25 03:00:00
5,289.73,289.11,64,2.82,5.19,0.00,0.00,0,2026-08-25 06:00:00
6,295.16,294.51,42,4.08,6.32,0.00,0.00,0,2026-08-25 09:00:00
7,298.15,297.52,31,4.21,4.92,0.00,0.00,0,2026-08-25 12:00:00
8,298.50,297.85,29,4.41,4.91,0.00,0.00,0,2026-08-25 15:00:00
9,294.69,293.89,38,3.05,6.82,0.00,0.00,0,2026-08-25 18:00:00
10,291.53,290.70,49,3.12,9.24,0.00,0.00,0,2026-08-25 21:00:00
11,289.88,288.99,53,3.16,9.07,0.00,0.00,0,2026-08-26 00:00:00
12,288.55,287.61,56,3.77,10.39,0.00,0.00,0,2026-08-26 03:00:00
13,290.33,289.70,61,4.51,9.93,0.00,0.00,0,2026-08-26 06:00:00
14,295.34,294.69,41,5.25,7.55,0.00,0.00,0,2026-08-26 09:00:00
15,298.21,297.58,31,4.85,5.64,0.00,0.00,0,2026-08-26 12:00:00
16,298.38,297.77,31,4.63,5.32,0.00,0.00,0,2026-08-26 15:00:00
17,296.04,295.40,39,3.59,6.87,0.00,0.00,0,2026-08-26 18:00:00
18,293.82,293.14,46,4.72,10.97,0.00,0.00,0,2026-08-26 21:00:00
19,292.46,291.73,49,5.20,13.44,0.00,0.00,0,2026-08-27 00:00:00
20,291.24,290.49,53,4.49,10.17,0.00,0.00,0,2026-08-27 03:00:00
21,291.26,290.56,55,4.82,10.98,0.00,0.00,0,2026-08-27 06:00:00
22,297.70,297.10,34,6.33,9.36,0.00,0.00,0,2026-08-27 09:00:00
23,301.19,300.19,28,6.32,7.70,0.00,0.00,0,2026-08-27 12:00:00
24,301.38,300.32,28,5.97,7.26,0.00,0.00,0,2026-08-27 15:00:00
25,297.97,297.47,37,4.95,10.07,0.00,0.00,0,2026-08-27 18:00:00
26,295.51,294.92,43,4.98,12.94,0.00,0.00,0,2026-08-27 21:00:00
27,293.99,293.41,49,5.18,13.41,0.00,0.00,0,2026-08-28 00:00:00
28,292.99,292.39,52,5.12,13.06,0.00,0.00,0,2026-08-28 03:00:00
29,293.09,292.45,50,3.67,10.55,0.00,0.00,0,2026-08-28 06:00:00
30,297.55,297.19,44,3.85,6.15,0.00,0.00,0,2026-08-28 09:00:00
31,299.51,299.51,55,4.21,6.09,0.00,0.00,0,2026-08-28 12:00:00
32,300.24,300.78,52,1.94,3.25,0.00,0.00,0,2026-08-28 15:00:00
33,297.51,297.59,61,0.95,1.46,0.31,0.25,0,2026-08-28 18:00:00
34,293.52,293.83,85,4.21,7.79,1.00,6.40,0,2026-08-28 21:00:00
35,291.50,291.85,94,3.46,6.59,1.00,6.22,0,2026-08-29 00:00:00
36,290.65,290.75,88,5.03,12.02,1.00,7.42,0,2026-08-29 03:00:00
37,290.70,290.76,86,4.67,9.07,1.00,2.02,0,2026-08-29 06:00:00
38,292.26,292.18,75,6.42,10.47,1.00,1.08,0,2026-08-29 09:00:00
39,293.91,293.74,65,4.65,7.04,1.00,1.86,0,2026-08-29 12:00:00

## All cities, all forecasts

Now let's expand one more time by adding a loop to handle each of our three cities.

In [38]:
cities_df

   city_id     name  country  latitude  longitude
0        1   Berlin  Germany   52.5200     13.405
1        2  Hamburg  Germany   53.5500     10.000
2        3   Munich  Germany   48.1375     11.575

In [46]:
forecasts = []
url = "https://api.openweathermap.org/data/2.5/forecast"

for _, row in cities_df.iterrows():
    params = {
        "lat": row["latitude"],
        "lon": row["longitude"],
        "appid": openweather_key,
        "units": "metric"
    }
    response = requests.get(url, params=params)
    response_json = response.json()

    for forecast in response_json['list']:
        forecast_data = {
            "temp": forecast['main']['temp'],
            "feels_like": forecast['main']['feels_like'],
            "humidity_%": forecast['main']['humidity'],
            "wind_speed": forecast['wind']['speed'],
            "wind_gust": forecast['wind']['gust'],
            "precipitation_%": forecast['pop'],
            "rain_3h": forecast.get('rain', {}).get('3h', 0),
            "snow_3h": forecast.get('snow', {}).get('3h', 0),
            "forecast_time": forecast['dt_txt'],
            "city_id": row["city_id"]
        }
        forecasts.append(forecast_data)

forecast_df = pd.DataFrame(forecasts)
forecast_df

,temp,feels_like,humidity_%,wind_speed,wind_gust,precipitation_%,rain_3h,snow_3h,forecast_time,city_id
0,20.58,20.34,63,1.43,1.68,0.00,0.00,0,2026-08-24 15:00:00,1
1,20.15,19.76,59,1.52,1.76,0.00,0.00,0,2026-08-24 18:00:00,1
2,18.42,17.83,58,1.45,1.62,0.00,0.00,0,2026-08-24 21:00:00,1
3,14.49,13.61,62,1.83,2.74,0.00,0.00,0,2026-08-25 00:00:00,1
4,13.72,12.90,67,2.05,3.68,0.00,0.00,0,2026-08-25 03:00:00,1
...,...,...,...,...,...,...,...,...,...,...
115,14.26,14.20,94,3.08,10.92,1.00,0.27,0,2026-08-29 00:00:00,3
116,13.84,13.66,91,4.06,13.16,0.34,0.16,0,2026-08-29 03:00:00,3
117,14.73,14.43,83,4.00,12.20,0.00,0.00,0,2026-08-29 06:00:00,3
118,20.02,19.44,52,6.40,10.26,0.00,0.00,0,2026-08-29 09:00:00,3
119,21.27,20.78,51,6.62,10.25,0.00,0.00,0,2026-08-29 12:00:00,3

In [47]:
# useful for writing the SQL table definition
forecast_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   temp             120 non-null    float64
 1   feels_like       120 non-null    float64
 2   humidity_%       120 non-null    int64
 3   wind_speed       120 non-null    float64
 4   wind_gust        120 non-null    float64
 5   precipitation_%  120 non-null    float64
 6   rain_3h          120 non-null    float64
 7   snow_3h          120 non-null    int64
 8   forecast_time    120 non-null    object
 9   city_id          120 non-null    int64
dtypes: float64(6), int64(3), object(1)
memory usage: 9.5+ KB

In [48]:
forecast_df.to_sql(
    "forecasts",
    con=connection_string,
    if_exists="append",
    index=False
)

120